language: node_js
node_js:
    - "6"
before_script:
    - yarn install
notifications:
    email: false
script:
    - npm run eslint
cache:
    yarn:
        - yarn
    directories:
        - node_modules
